# Generated by Django 2.0 on 2019-11-17 04:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=30, verbose_name='用户昵称')),
                ('presentence', models.TextField(max_length=140, verbose_name='个人宣言')),
                ('location', models.TextField(max_length=50, verbose_name='居住地址')),
                ('university', models.CharField(max_length=50, verbose_name='就读学校')),
            ],
        ),
        migrations.CreateModel(
            name='Sen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='分享标题')),
                ('content', models.TextField(max_length=500, verbose_name='分享内容')),
                ('sharetime', models.DateField(auto_now_add=True)),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Myusers', verbose_name='分享人')),
            ],
        ),
    ]
