# Generated by Django 2.0 on 2019-11-17 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='myusers',
            name='pwd',
            field=models.CharField(default=None, max_length=20, verbose_name='密码'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='myusers',
            name='username',
            field=models.CharField(default=None, max_length=20, verbose_name='用户名'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='myusers',
            name='location',
            field=models.TextField(default='暂未设置住址', max_length=50, verbose_name='居住地址'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='nickname',
            field=models.CharField(default='暂未设置昵称', max_length=30, verbose_name='用户昵称'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='presentence',
            field=models.TextField(default='暂未设置宣言', max_length=140, verbose_name='个人宣言'),
        ),
        migrations.AlterField(
            model_name='myusers',
            name='university',
            field=models.CharField(default='暂未设置学校', max_length=50, verbose_name='就读学校'),
        ),
    ]
