# Generated by Django 2.0 on 2020-01-11 07:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Myusers',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=20, verbose_name='用户名')),
                ('pwd', models.CharField(max_length=20, verbose_name='密码')),
                ('nickname', models.CharField(default='暂未设置昵称', max_length=30, verbose_name='用户昵称')),
                ('presentence', models.TextField(default='暂未设置宣言', max_length=140, verbose_name='个人宣言')),
                ('location', models.TextField(default='暂未设置住址', max_length=50, verbose_name='居住地址')),
                ('university', models.CharField(default='暂未设置学校', max_length=50, verbose_name='就读学校')),
            ],
        ),
        migrations.CreateModel(
            name='Sen',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='分享标题')),
                ('content', models.TextField(max_length=500, verbose_name='分享内容')),
                ('sharetime', models.DateField(auto_now_add=True)),
                ('sentype', models.CharField(default='优美语句', max_length=10, verbose_name='句子类别')),
                ('sharer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='index.Myusers', verbose_name='分享人')),
            ],
        ),
    ]
